WARNING:  WatchFiles detected changes in 'orderPricePlan/routes.py'. Reloading...
Process SpawnProcess-31:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/projects/fastapi/crm_middleware/main.py", line 2, in <module>
    from orderPricePlan.routes import router as orderPricePlanRoutes
  File "/opt/projects/fastapi/crm_middleware/orderPricePlan/routes.py", line 4, in <module>
    from .services import ChangeSubOffering
ImportError: cannot import name 'ChangeSubOffering' from 'orderPricePlan.services' (/opt/projects/fastapi/crm_middleware/orderPricePlan/services.py)
WARNING:  WatchFiles detected changes in 'orderPricePlan/routes.py'. Reloading...
Process SpawnProcess-32:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/projects/fastapi/crm_middleware/main.py", line 2, in <module>
    from orderPricePlan.routes import router as orderPricePlanRoutes
  File "/opt/projects/fastapi/crm_middleware/orderPricePlan/routes.py", line 4
    from .services import 
                          ^
SyntaxError: invalid syntax
WARNING:  WatchFiles detected changes in 'orderPricePlan/routes.py'. Reloading...
Process SpawnProcess-33:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/projects/fastapi/crm_middleware/main.py", line 2, in <module>
    from orderPricePlan.routes import router as orderPricePlanRoutes
  File "/opt/projects/fastapi/crm_middleware/orderPricePlan/routes.py", line 4
    from .services import 
                          ^
SyntaxError: invalid syntax
WARNING:  WatchFiles detected changes in 'orderPricePlan/routes.py'. Reloading...
INFO:     Started server process [2316355]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:40406 - "POST /orderPricePlan HTTP/1.1" 307 Temporary Redirect
cbs_response: b'<?xml version="1.0" encoding="utf-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><bcs:ChangeSubOfferingResultMsg xmlns:bcs="http://www.huawei.com/bme/cbsinterface/bcservices" xmlns:cbs="http://www.huawei.com/bme/cbsinterface/cbscommon" xmlns:bcc="http://www.huawei.com/bme/cbsinterface/bccommon"><ResultHeader><cbs:Version>1</cbs:Version><cbs:ResultCode>0</cbs:ResultCode><cbs:ResultDesc>Operation successfully.</cbs:ResultDesc></ResultHeader><ChangeSubOfferingResult><bcs:AddOffering><bcs:OfferingKey><bcc:OfferingID>785632384</bcc:OfferingID><bcc:PurchaseSeq>40217227612iiu107</bcc:PurchaseSeq></bcs:OfferingKey><bcs:EffectiveTime>20241002114621</bcs:EffectiveTime><bcs:ExpirationTime>20370101000000</bcs:ExpirationTime><bcs:RentDeductionStatus>0</bcs:RentDeductionStatus></bcs:AddOffering><bcs:RentDeductionResult><bcs:FreeUnitChangeList><bcs:OwnerType>S</bcs:OwnerType><bcs:OwnerKey>9235000018</bcs:OwnerKey><bcs:FreeUnitChgInfo><bcs:FreeUnitInstanceID>133000000000000237</bcs:FreeUnitInstanceID><bcs:FreeUnitType>C_test_voice</bcs:FreeUnitType><bcs:FreeUnitTypeName>test_voice</bcs:FreeUnitTypeName><bcs:MeasureUnit>1003</bcs:MeasureUnit><bcs:MeasureUnitName>Seconds</bcs:MeasureUnitName><bcs:OldAmt>5000</bcs:OldAmt><bcs:NewAmt>5000</bcs:NewAmt><bcs:OfferingKey><bcc:OfferingID>785632384</bcc:OfferingID><bcc:PurchaseSeq>40217227612iiu107</bcc:PurchaseSeq></bcs:OfferingKey></bcs:FreeUnitChgInfo></bcs:FreeUnitChangeList></bcs:RentDeductionResult></ChangeSubOfferingResult></bcs:ChangeSubOfferingResultMsg></soapenv:Body></soapenv:Envelope>'
INFO:     127.0.0.1:40406 - "POST /orderPricePlan/ HTTP/1.1" 200 OK
WARNING:  WatchFiles detected changes in 'orderPricePlan/routes.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2316355]
INFO:     Started server process [2316982]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'orderPricePlan/handlers.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2316982]
INFO:     Started server process [2317107]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'orderPricePlan/handlers.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2317107]
INFO:     Started server process [2317174]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'utils/soap_client.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2317174]
INFO:     Started server process [2317299]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'utils/soap_client.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2317299]
Process SpawnProcess-39:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/projects/fastapi/crm_middleware/main.py", line 2, in <module>
    from orderPricePlan.routes import router as orderPricePlanRoutes
  File "/opt/projects/fastapi/crm_middleware/orderPricePlan/routes.py", line 2, in <module>
    from .handlers import generate_response, ChangeSubOffering
  File "/opt/projects/fastapi/crm_middleware/orderPricePlan/handlers.py", line 8, in <module>
    from utils.soap_client import soap_client
  File "/opt/projects/fastapi/crm_middleware/utils/soap_client.py", line 13
    return response.content
    ^^^^^^
IndentationError: expected an indented block after 'if' statement on line 12
WARNING:  WatchFiles detected changes in 'utils/soap_client.py'. Reloading...
Process SpawnProcess-40:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/projects/fastapi/crm_middleware/main.py", line 2, in <module>
    from orderPricePlan.routes import router as orderPricePlanRoutes
  File "/opt/projects/fastapi/crm_middleware/orderPricePlan/routes.py", line 2, in <module>
    from .handlers import generate_response, ChangeSubOffering
  File "/opt/projects/fastapi/crm_middleware/orderPricePlan/handlers.py", line 8, in <module>
    from utils.soap_client import soap_client
  File "/opt/projects/fastapi/crm_middleware/utils/soap_client.py", line 13
    return response.content
    ^^^^^^
IndentationError: expected an indented block after 'if' statement on line 12
WARNING:  WatchFiles detected changes in 'utils/soap_client.py'. Reloading...
Process SpawnProcess-41:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/projects/fastapi/crm_middleware/main.py", line 2, in <module>
    from orderPricePlan.routes import router as orderPricePlanRoutes
  File "/opt/projects/fastapi/crm_middleware/orderPricePlan/routes.py", line 2, in <module>
    from .handlers import generate_response, ChangeSubOffering
  File "/opt/projects/fastapi/crm_middleware/orderPricePlan/handlers.py", line 8, in <module>
    from utils.soap_client import soap_client
  File "/opt/projects/fastapi/crm_middleware/utils/soap_client.py", line 13
    return response.content
    ^^^^^^
IndentationError: expected an indented block after 'if' statement on line 12
WARNING:  WatchFiles detected changes in 'utils/soap_client.py'. Reloading...
Process SpawnProcess-42:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/projects/fastapi/crm_middleware/main.py", line 2, in <module>
    from orderPricePlan.routes import router as orderPricePlanRoutes
  File "/opt/projects/fastapi/crm_middleware/orderPricePlan/routes.py", line 2, in <module>
    from .handlers import generate_response, ChangeSubOffering
  File "/opt/projects/fastapi/crm_middleware/orderPricePlan/handlers.py", line 8, in <module>
    from utils.soap_client import soap_client
  File "/opt/projects/fastapi/crm_middleware/utils/soap_client.py", line 15
    raise HTTPException(status_code=response.status_code, detail="Bad content")
    ^^^^^
IndentationError: expected an indented block after 'else' statement on line 14
WARNING:  WatchFiles detected changes in 'utils/soap_client.py'. Reloading...
INFO:     Started server process [2317407]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'utils/soap_client.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2317407]
INFO:     Started server process [2317473]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'orderPricePlan/handlers.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2317473]
INFO:     Started server process [2317565]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'utils/soap_client.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2317565]
INFO:     Started server process [2317654]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'utils/soap_client.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2317654]
INFO:     Started server process [2317658]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'orderPricePlan/handlers.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2317658]
INFO:     Started server process [2317825]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'orderPricePlan/handlers.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2317825]
INFO:     Started server process [2317855]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'orderPricePlan/handlers.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2317855]
INFO:     Started server process [2317879]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'orderPricePlan/handlers.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2317879]
INFO:     Started server process [2317934]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'orderPricePlan/handlers.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2317934]
INFO:     Started server process [2317957]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'orderPricePlan/handlers.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2317957]
Process SpawnProcess-53:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/projects/fastapi/crm_middleware/main.py", line 2, in <module>
    from orderPricePlan.routes import router as orderPricePlanRoutes
  File "/opt/projects/fastapi/crm_middleware/orderPricePlan/routes.py", line 2, in <module>
    from .handlers import generate_response, ChangeSubOffering
ImportError: cannot import name 'generate_response' from 'orderPricePlan.handlers' (/opt/projects/fastapi/crm_middleware/orderPricePlan/handlers.py)
WARNING:  WatchFiles detected changes in 'orderPricePlan/handlers.py'. Reloading...
INFO:     Started server process [2318053]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:35946 - "POST /orderPricePlan HTTP/1.1" 307 Temporary Redirect
INFO:     127.0.0.1:35946 - "POST /orderPricePlan/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:35946 - "POST /orderPricePlan HTTP/1.1" 307 Temporary Redirect
INFO:     127.0.0.1:35946 - "POST /orderPricePlan/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/opt/projects/fastapi/crm_middleware/orderPricePlan/routes.py", line 12, in orderPricePlanOffer
    result = generate_response(CBS_response)
  File "/opt/projects/fastapi/crm_middleware/orderPricePlan/handlers.py", line 25, in generate_response
    result =  Body.find(f'.//{{{ch_body.nsmap["bcc"]}}}OfferingID')
KeyError: 'bcc'
WARNING:  WatchFiles detected changes in 'orderPricePlan/handlers.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2318053]
INFO:     Started server process [2323316]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'orderPricePlan/services.py', 'orderPricePlan/schemas.py', 'orderPricePlan/routes.py', 'orderPricePlan/handlers.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2323316]
INFO:     Started server process [2338459]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'utils/soap_client.py', 'utils/common.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2338459]
INFO:     Started server process [2338463]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'orderPricePlan/handlers.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2338463]
INFO:     Started server process [2338734]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'orderPricePlan/handlers.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2338734]
INFO:     Started server process [2338764]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'orderPricePlan/handlers.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2338764]
INFO:     Started server process [2338833]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'orderPricePlan/handlers.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2338833]
INFO:     Started server process [2338883]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'orderPricePlan/handlers.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2338883]
Process SpawnProcess-62:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/projects/fastapi/crm_middleware/main.py", line 2, in <module>
    from orderPricePlan.routes import router as orderPricePlanRoutes
  File "/opt/projects/fastapi/crm_middleware/orderPricePlan/routes.py", line 6, in <module>
    from .handlers import separationDoServiceOrderPricePlan, send_request, generate_response
  File "/opt/projects/fastapi/crm_middleware/orderPricePlan/handlers.py", line 157
    from xml.dom import minidom 
    ^^^^
IndentationError: expected an indented block after function definition on line 152
WARNING:  WatchFiles detected changes in 'orderPricePlan/handlers.py'. Reloading...
Process SpawnProcess-63:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/projects/fastapi/crm_middleware/main.py", line 2, in <module>
    from orderPricePlan.routes import router as orderPricePlanRoutes
  File "/opt/projects/fastapi/crm_middleware/orderPricePlan/routes.py", line 6, in <module>
    from .handlers import separationDoServiceOrderPricePlan, send_request, generate_response
  File "/opt/projects/fastapi/crm_middleware/orderPricePlan/handlers.py", line 155
    
    ^
IndentationError: expected an indented block after function definition on line 152
WARNING:  WatchFiles detected changes in 'orderPricePlan/handlers.py'. Reloading...
Process SpawnProcess-64:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/projects/fastapi/crm_middleware/main.py", line 2, in <module>
    from orderPricePlan.routes import router as orderPricePlanRoutes
  File "/opt/projects/fastapi/crm_middleware/orderPricePlan/routes.py", line 6, in <module>
    from .handlers import separationDoServiceOrderPricePlan, send_request, generate_response
  File "/opt/projects/fastapi/crm_middleware/orderPricePlan/handlers.py", line 160
    
    ^
IndentationError: expected an indented block after function definition on line 157
WARNING:  WatchFiles detected changes in 'orderPricePlan/handlers.py'. Reloading...
Process SpawnProcess-65:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/projects/fastapi/crm_middleware/main.py", line 2, in <module>
    from orderPricePlan.routes import router as orderPricePlanRoutes
  File "/opt/projects/fastapi/crm_middleware/orderPricePlan/routes.py", line 6, in <module>
    from .handlers import separationDoServiceOrderPricePlan, send_request, generate_response
  File "/opt/projects/fastapi/crm_middleware/orderPricePlan/handlers.py", line 156
    
    ^
IndentationError: expected an indented block after function definition on line 153
WARNING:  WatchFiles detected changes in 'orderPricePlan/handlers.py'. Reloading...
Process SpawnProcess-66:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
  File "/opt/projects/fastapi/crm_middleware/.venv/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/projects/fastapi/crm_middleware/main.py", line 2, in <module>
    from orderPricePlan.routes import router as orderPricePlanRoutes
  File "/opt/projects/fastapi/crm_middleware/orderPricePlan/routes.py", line 6, in <module>
    from .handlers import separationDoServiceOrderPricePlan, send_request, generate_response
  File "/opt/projects/fastapi/crm_middleware/orderPricePlan/handlers.py", line 157, in <module>
    name = doc.getElementsByTagName("name")[0]
NameError: name 'doc' is not defined
WARNING:  WatchFiles detected changes in 'orderPricePlan/handlers.py'. Reloading...
INFO:     Started server process [2339245]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'orderPricePlan/handlers.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2339245]
INFO:     Started server process [2339304]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'orderPricePlan/handlers.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2339304]
INFO:     Started server process [2339638]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'orderPricePlan/handlers.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2339638]
INFO:     Started server process [2339844]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'orderPricePlan/handlers.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2339844]
INFO:     Started server process [2339949]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'orderPricePlan/handlers.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2339949]
INFO:     Started server process [2340035]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'orderPricePlan/routes.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2340035]
INFO:     Started server process [2340206]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'orderPricePlan/routes.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2340206]
INFO:     Started server process [2340227]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'orderPricePlan/routes.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2340227]
INFO:     Started server process [2340276]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'orderPricePlan/routes.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2340276]
INFO:     Started server process [2340309]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'orderPricePlan/routes.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2340309]
INFO:     Started server process [2340350]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
